### ISSUE TITLE
CONFIG :: Heroku Production Checklist

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/dash-and-do-github#20]
# [`CONFIGURATION`](): Production Checklist

> List only Public | Well Known Configuration Steps
>
> -   https://github.com/iPoetDev/dash-and-do-github/labels/Focus%3A%20Project%20Repository
> -   https://github.com/iPoetDev/dash-and-do-github/labels/Focus%3A%20Build%20Integration
> -   https://github.com/iPoetDev/dash-and-do-github/labels/Focus%3A%20Front-End%20Client
> -   https://github.com/iPoetDev/dash-and-do-github/labels/Focus%3A%20Back%20End%20Server
> -   https://github.com/iPoetDev/dash-and-do-github/labels/Focus%3A%20Backing%20DB%20Services

<small>Do not list harming or insecure confidential configurations that may pose a risk</small>

***

- [ ] Production Check 
    - [ ] PASSED Heroku-22 Stack
    - [ ] SKIPPED Eco Dynos: 
        - [ ] No running dynos.
    - [ ] SKIPPED Dyno Redundancy: 
        - [ ] No web processes.
    - [ ] SKIPPED Production Postgres Database: 
        - [ ] No postgres database.
    - [ ] SKIPPED Postgres High Availability: 
       - [ ] No postgres database.
    - [ ] FAILED App monitoring: Not using an app monitoring add-on. 
        - [ ] Install a [monitoring add-on](https://elements.heroku.com/search?q=monitoring) such as
        - [ ] [New Relic](https://elements.heroku.com/addons/newrelic) or 
        - [ ] [Librato](https://elements.heroku.com/addons/librato) to monitor your app's performance.
   - [ ] FAILED Log monitoring: 
        - [ ] No logging add-on found. 
        - [ ] Install a [logging add-on](https://elements.heroku.com/addons#logging) to monitor and search your logs.
   - [ ] WARNING Custom Maintenance Pages. 
        - [ ] Configure customized error and maintenance pages to match your app's branding.
   - [ ] SKIPPED Heroku SSL: Heroku SSL is not enabled.
