### ISSUE TITLE
 SPRINT :: 02 [5 Days] : "The Arch n Deploy" : - W/S: 23-JUL-17 | W/E: JUL-21 #DESIGN

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/dash-and-do-github#4]
# [`SPRINT - Milestone: Agile Plan | Control`](https://github.com/iPoetDev/dash-and-do-github/milestone/2)
> - [x] Replace Milestone Id in link.
> - [x] Add Sprint Sequence Id in Title.
> - [x] Copy Sprint label per sprint.
  https://github.com/iPoetDev/dash-and-do-github/labels/Sprint%2002%20%3A%20Arch%20n%20Deploy

> https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Sprint
> https://github.com/iPoetDev/dash-and-do-github/labels/Plan%20%3A%20Horizon: 3 Weeks

## Spint Backlog
> Add Planned Issues Below

**VIEWS**: <small>Replace Project ID in link,</small>
- [x] Project: **` 21 `** [AGILE - PLANNER](https://github.com/users/iPoetDev/projects/21)
|

https://github.com/iPoetDev/dash-and-do-github/labels/Backlog%3A%20Agile%20%26%20Planner
- [x] EpicLog | Sprint Log: **` Milestone 2 `** [AGILE Plan | Control](https://github.com/iPoetDev/dash-and-do-github/milestone/2) 

---

## Sprint Plan | Report

- [ ] Backlog: [Agile - Planner](https://github.com/iPoetDev/dash-and-do-github/milestone/2)
  https://github.com/iPoetDev/dash-and-do-github/labels/Backlog%3A%20Agile%20%26%20Planner
  - [x] iPoetDev/dash-and-do-github#7 
  - [ ] iPoetDev/dash-and-do-github#14 
  - [x] iPoetDev/dash-and-do-github#19 
  - [ ] iPoetDev/dash-and-do-github#20 
  - [x] iPoetDev/dash-and-do-github#21 
  - [x] iPoetDev/dash-and-do-github#23 
  - [x] iPoetDev/dash-and-do-github#24 
  - [ ] iPoetDev/dash-and-do-github#25 
- [ ] Epic: " The Arch & Deploy "
  https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Epic

- [ ] Features:
  https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Feature
  - N/a :
  - n/a :
- [ ] Stories:
  https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Story
  - [x] iPoetDev/dash-and-do-github#18 
  - [ ] iPoetDev/dash-and-do-github#25
  - [x] iPoetDev/dash-and-do-github#26
  - [ ] iPoetDev/dash-and-do-github#27 
  - [ ] iPoetDev/dash-and-do-github#28 
  - [ ] iPoetDev/dash-and-do-github#29 
  - [ ] iPoetDev/dash-and-do-github#30 
  - [ ] iPoetDev/dash-and-do-github#31 
- [ ] Acceptance: The following have reached Accepted for UAC
  https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Accept
  -  :
  -  :   
- [ ] Progress:
  - Planned: 1 
  - Started:
  - Not Completed:
  - Completed:
  - Moved Next:

---
##### Sources

- https://zube.io/blog/agile-project-management-workflow-for-github-issues/
