### ISSUE TITLE
STORY-000? :: As a developer, I need to inspect and refine the GitHub API

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/dash-and-do-github#50]
# **[`USER STORY STATEMENT`]()**: Inspect, Learn and Refine the GitHub API options.

> `User Case` | `Epic's Task` | `Enabler Task`

**`STORY`**:

```
As a: developer,
I/We need: to inspect and refine the GitHub API for the solutions Use Case and Concept as a Candidate Datasource
  And: Read the GitHub API documentation to take notes.
So That/Because: 
- the GitHub API has fair to many applications program interfaces 
- has a steep learning curve 
- has a large documentation scope and depth, with many rules

Type of: Epic Task & Enabler Task
```

- [x] Read the GitHub Document API: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28

---

## Acceptance Criteria:

-   Link: **[`UAC-000?`](https://github.com/iPoetDev/)**
-   [x] Status: ~~`Proposed` |~~ `Prepared` | ~~`Pending` | `Tested` | `Accepted` | `Rejected` | `Superseded` | `Reverted`~~
-   [x] Definition of Done: `Pending` | ~~`Complete`~~

```
Given: That the GitHub API documentation is inspected, 
When: The GitHub API is refined and defined enough to decide to proceed with this use case 
Then: We can proceed with the use case for the GitHub Dash and Do solution as a proof of concept.
```

### Related

> **[`ADR-000?`](https://github.com/iPoetDev/)** || **[`EPIC-000?`](https://github.com/iPoetDev/)** || **[`FEATURE-000?`](https://github.com/iPoetDev/)**
