### ISSUE TITLE
DEFINE: `ACCOUNTS`: Django App + Front End: User Registration & Login System

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/dash-and-do-github#53]
# `[DEFINE]()`: A User Registration, Login System for a User Profile and Data Model
> PROJECT | SOLUTION: Concept | Idea Capture | Discovery | Document Driven Effort

- [x] Ideation, Concept
- [x] Research
- [x] Agile Planning
  - [x] ADR: Any Decision Records / Requirements 
  - [x] Epic:
  - [x] Feature:
  - [ ] Components:
  - [x] Stories 
  - [x] Acceptance
     - [x] UAC Test case: 
- [x] Readme
  - [ ] Writing
  - [ ] Diagramming
- [ ] Proofing
- [ ] Editorial

>> - This DEFINE issue is the overall Product/Component Definition Document (Or Requirement Work Specification) that lists and summaries the Component & Deliverables to be scoped for the statement of effort.

## Idea

```text
In the context of learning from other's prior art efforts,
As a developer, I want to understand the steps and features 
To design and develop a Django component (a Django app) 
 - For a User Registration & Login System.
 - For a User Profile that is a User controlled and is CRUD data model driven
 - For Account security controls and recovery
 - For an Administrators to CRUD Users
```
## Research
> Sources

- [Perplexity.AI: What Sources and Tutorials are to add a GitHub Login to a Django Web App](https://www.perplexity.ai/search/71a0ddd4-3648-4b9f-86e4-a36cafd04a3d?s=c)
- [GitHub.com: Django registration and login system](https://github.com/earthcomfy/Django-registration-and-login-system)
- [Dev.To: Django Registration/Login App Series Articles](https://dev.to/earthcomfy/series/14274)

### ADR: Any Decision Records
> Related Decisions | Requirements

- ADR000X: Select a Django package for Data Drive Forms.
- ADR000X: Select a Django package for standard Authentication, Authorisation and Role Based Access backend and processes.
- ADR000X: Select a Django package for social Authentication for GitHub Account integration/backends
- ADR000X: Select a Django package for password validation & hashing (grouped of related choices).
- ADR000X: Select a Django Session Engines

### Epic
> Key Epic Story | Theme | Requirement

- [x] **`GitHub Integration`**: For new Developers who have GitHub accounts, who want to integrate their GitHub account and have this securely managed by OUR Dash & Do GitHub Manager as a helpful resource as a single pane of glass view that provides information and secures a social login with GitHub as an Identity provider, so it protects these next two following epics, and associated features (see below).

#### Related | Added Context

>> **`GitHub Repositories Reporting`**: For new Developers who have GitHub accounts, who want to have a dashboard overview of their GitHub account, and repositories in bulk, and have this securely managed by OUR Dash & Do GitHub Manager as a helpful resource as a single pane of glass view that provides information and a report on the state of their repositories at a single glance. 
>>  **`GitHub Repositories Tasks`**: For new Developers who have GitHub accounts, who want to have an bulk activity manager of their GitHub repositories, and have this securely managed by OUR Dash & Do GitHub Manager as a helpful resource as a single pane of glass view that provides information and tasks to update the state of their repositories at a single action or in as few minimal steps as possible over a number of repositories.

***
> ===================================================================
***

### Feature
> Source: https://github.com/earthcomfy/Django-registration-and-login-system#basic-features-of-the-app

**`In Focus`**:

- [ ] **`Register`** – Users can register and create a new profile
- [ ] **`Login `**- Registered users can login using username and password
- [ ] **`User Profile`** - Once logged in, users can create and update additional information such as avatar and bio in the profile page
- [ ] **`Update Profile`** – Users can update their information such as username, email, password, avatar and bio
- [ ] **`Remember me`** – Cookie Option, users don’t have to provide credentials every time they hit the site
- [ ] **`Forgot Password`** – Users can easily retrieve their password if they forget it
- [ ] **`Admin Panel`** – admin can CRUD users
 
<small>`Above text is a direct extract from Hana Belay (GitHub @earthcomfy) Readme`. See Sources above.</small>

**`Related`**
> 

iPoetDev/dash-and-do-github#49 - See the Features for the Social Account Integration

***
> ===================================================================
***

### Components 

- [ ] Django Libraries (Once ADR are recorded).
    - [ ] 
- [ ] Django Authentication
- [ ] Django Session Engines
- [ ] Django Templates
- [ ] Django Forms
- [ ] Data Models
   - [ ] Django User Profile
   - [ ] (Optional) Django User Custom Model
- [ ] Django Admin Panel
- [ ] Django Settings
- [ ] Environmental Variables
- [ ] Managed DBaaS

***
> ===================================================================
***

#### **`Registration User Flow`** for the feature: Register.
- [ ] #54
- [ ] #66 
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Core Login User Flow`** for the feature: Login
- [ ] #83
- [ ]  #67
- [ ]  #68 
- [ ] #84
- [ ] #85
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Forgot Login User Flow`** for the feature: Forgot Password.
- [ ] #69 
- [ ] #70 
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Sessions User Flow`** for the feature: Remember me feature.
- [ ] #71 
- [ ] #73
- [ ] #74
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Account User Flow`** for the features of i) User Profile and ii) Update Profiles.
- [ ] #75
- [ ] #76
         - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Account User Flow`**  for the features of i) User Profile and ii) Update Profiles.
- [ ] #77
- [ ] #78
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Admin Account User Flow`**  for the feature: Admin Panel
- [ ] #79
- [ ] #80

***
> ===================================================================
***

### User Acceptance 
> Summary | See Individual or Groups UAC and UAT issues. | Happy Path Testing

- [ ] **`Registration User Flow`**: In the scenario of user registration of unknown or new users to the site with the intent to create a new account, then the expected outcome for a new user is to successfully register with the app/web service, and to have received a verification email to confirm the account.
    - _UA Test_: `As a user, I should be able to register a new account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Core Login User Flow`**: In the scenario of user login and authorisation of known existing users of the site, previous verified and registered, then the expected outcome for a verified known user is to successfully access with the service and to access their own user profile (i.e. the user account).
    - _UA Test_: `As a user, I should be able to login my own account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Forgot Login User Flow`**: In the scenario of forgotten user login and unable to authorisation of known existing users of the site, then the expected outcome of a forgotten password is the successful retrieval of a forgotten password link, and then the successful reset of a new password associated with the correct user and then confirmation that the user can use the new password to access their account again.
    - _UA Test_: `As a user, I should be able to reset a password to my own account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Session Management User Flow`**: In the scenario of the session and user state-based web access control and permissions, then the user should be able to stay logged in once logged in and authenticated and use the remember the user on return visits and until the cookie value is cleared or the account is timed out.
    - _UA Test_: `As a user, I should be able to leave and review the web between session, and not have re-login/re-authenticate to my account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Account User Flow`**: In the scenario of an authenticated and authorised service user wanting to manage and control their account, then the user can access and read their profile and then make additions, edits to fields of their profile as well as delete or remove data.
    - _UA Test_: `As a user, I should be able to access and read my own account's profile page on the Dash and Do GItHub web app`.
    - _UA Test_: `As a user, I should be able to edit and update my own account's profile page on the Dash and Do GItHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Delete Account User Flow`** In the scenario of an authenticated service user wanting to delete their account, then the user should be allowed to delete their account and be warned that this account is permanent as well as get a confirmation that their account was deleted. 
    -  _UA Test_: `As a user, I should be able to delete and remote my own account's profile data on the Dash and Do GitHub web app`.
     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **Admin User Flow`**: In the scenario of an administrator of all Dash and Do GitHub web app users, the the admin user should be able to create, view, list, edit, remove existing user profiles and or modify specific limited user fields.
    -  _UA Test_: `As an admin user, I should be able to CRUD all users' profile on the Dash and Do GitHub web app`.

***
> ===================================================================
***

### Assessment Criteria
> Meets the following

- [4.03: PASS & MERIT: Access, Authentication & Authorisations](https://github.com/iPoetDev/dash-and-do-github/wiki/4.03:-PASS-&-MERIT:-Access,-Authentication-&-Authorisations-%E2%9D%93%E2%9C%94)
  - 3.1: Apply role-based login and registration functionality
  - 3.2: The current login state is reflected to the user
  - 3.3: Users should not be permitted to access restricted content and to access the functionality.

## Readme

- Header:
- Tags:
- Notes:

## Proof
> Grammar, Spelling, Diagram, 

## Editorial

- Include
- Edit
- Exclude

**Comment by iPoetDev** [comment]
# Commit 
#a80c66c: [app(config): D&D Settings Full Specification](https://github.com/iPoetDev/dash-and-do-github/commit/a80c66cac958953f72cedca99069ede71eb4a226)
- Sets up the foundations for the core pages, with placeholders and explicit defaults set.
- [x] 01: Imports
  - [x] 02: Base Paths
  - [x] 03: Project Structure
  - [x] 04: Environmental Variables
  - [x] 05: Key & Mode (Security)
  - [x] 06: Server, HTTP, Hosting
  - [x] 07: Applications
  - [x] 08: Middleware
  - [x] 09: Templates
  - [x] 10: Migrations
  - [ ] 11: Database
    - [ ] 11.1: Development.py
    - [ ] 11.2: Production.py
  - [ ] 12: Authentication
  - [x] 13: Inter8n & Formats
  - [x] 14: Data Limits
  - [ ] 15: Files & Uploads
    - [ ] 15.1: Media
    - [ ] 15.2: Static
  - [ ] 16: Email & Notifications
  - [ ] 17: Error Handling
  - [x] 18: Logging
  - [ ] 19: Security
  - [ ] 20: Proxy & Routing
  - [ ] 21: Signing
  - [ ] 22: Cookies & Sessions
  - [ ] 23: Third Party (import
- note:

**Comment by iPoetDev** [comment]
# Commit 
#a80c66c: [app(config): D&D Settings Full Specification](https://github.com/iPoetDev/dash-and-do-github/commit/a80c66cac958953f72cedca99069ede71eb4a226)
- Sets up the foundations for the core pages, it placeholders and explict defaults set..
- [x] 01: Imports
  - [x] 02: Base Paths
  - [x] 03: Project Structure
  - [x] 04: Environmental Variables
  - [x] 05: Key & Mode (Security)
  - [x] 06: Server, HTTP, Hosting
  - [x] 07: Applications
  - [x] 08: Middleware
  - [x] 09: Templates
  - [x] 10: Migrations
  - [ ] 11: Database
    - [ ] 11.1: Development.py
    - [ ] 11.2: Production.py
  - [ ] 12: Authentication
  - [x] 13: Inter8n & Formats
  - [x] 14: Data Limits
  - [ ] 15: Files & Uploads
    - [ ] 15.1: Media
    - [ ] 15.2: Static
  - [ ] 16: Email & Notifications
  - [ ] 17: Error Handling
  - [x] 18: Logging
  - [ ] 19: Security
  - [ ] 20: Proxy & Routing
  - [ ] 21: Signing
  - [ ] 22: Sessions
      - [ ] 22.1: CSRF Cookies & Sessions
  - [ ] 23: Third Party (import
- note:
