### ISSUE TITLE
REFINE: `CORE`: Web App Landing Page, Forms & Impressum: A Container, Home URL, & Registration for Dash & Do GitHub 

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/dash-and-do-github#55]
# `[REFINE`: Web App Landing Page, Forms & Impressum: A Hero Container, Home URL, & Registration for Dash & Do GitHub](https://github.com/iPoetDev/dash-and-do-github/issues/55) 

> PROJECT | SOLUTION: Concept | Idea Capture | Discovery | Document Driven Effort

-   [x] Ideation, Concept
-   [x] Research
-   [x] Agile Planning
    - [x] ADR
    - [x] Epic
    - [x] Feature
    - [x] Components
    - [x] Stories
        - [x] 🔢 Options
            - [x] 👍🏽 Benefits
            - [x] 👎🏽 Trade-Offs
            - [x] ⛏️ Uses: Components  
    - [x] Acceptance
        - [x] 🧪 Test Case: 
        - [ ] 🎯 Test State:
    - [x] Assessment 
-   [ ] Readme
    -   [ ] Writing
    -   [ ] Diagramming
-   [ ] Proofing
-   [ ] Editorial

- DEFINE document acts as internal Product/Feature/Component Definition Document and a statement of effort and Idea capture and specification.

## Idea

```text
A single landing (home) page (as a single page architecture)
  - web service URL (Domain)
  - with an in-page navigation (jump, header, floating, footer).
- that has a hero section on the top third;
- that has a call to action on the middle third
  - and offers the service registration or login form, 
  - with GitHub Integration
- that has an informative about on the lower third 
  - and contact form section.
```

***
>
***

## Research

> Sources

- Perplexity. Ai, 2023-Aug-01, ["What sources and or tutorials are there to host multiple forms on a single page as home page and call to actions using HTMX and Django templates"](https://www.perplexity.ai/search/8b4988f1-8f4f-4aac-b45d-bff508509cb9?s=c)
-

### ADR: Any Decision Records | Requirements

***
>
***

### Epic

- [x] **`Web App Singe Home Page`**: _For_ Software Developers as GitHub Users ... _Who_ want to review, report and do bulk activity on their GitHub Account; _Our_ Dash and Do GitHub Manager website/web app _Is a_ helpful website home page _That_ provides home page for the service, useful in place (no reload) registration & login form, and offers integration with GitHub via social accounts _As Well As_ an informative About & Contact [Page | Section] _On a_ single web page.

**`Categorisation`**: Front End, Web Client, HTML Page, Web/HTML Forms

#### Related | Added Context

>>  `GitHub Integration`: For new Developers who have GitHub accounts, who want to integrate their GitHub account and have this securely managed by OUR Dash & Do GitHub Manager as a helpful resource as a single pane of glass view that provides information and secures a social login with GitHub as an Identity provider, so it protects these next two following epics, and associated features (see below). 
    - See the [Define: Issue #53](https://github.com/iPoetDev/dash-and-do-github/issues/53)
>> `GitHub Repositories Reporting`: For new Developers who have GitHub accounts, who want to have a dashboard overview of their GitHub account, and repositories in bulk, and have this securely managed by OUR Dash & Do GitHub Manager as a helpful resource as a single pane of glass view that provides information and a report on the state of their repositories at a single glance.
>> `GitHub Repositories Tasks`: For new Developers who have GitHub accounts, who want to have an bulk activity manager of their GitHub repositories, and have this securely managed by OUR Dash & Do GitHub Manager as a helpful resource as a single pane of glass view that provides information and tasks to update the state of their repositories at a single action or in as few minimal steps as possible over a number of repositories.

***
>
***

### Feature

- Feature 

**`In Focus`**

- [ ] `Home Page URL/Domain`: Users can find and locate the web service using the URL/brand ID
- Hero Section: Users can get an immediate impression about the brand Id of the web service
  - [ ] Hero Banner
  - [ ] Branding. 
- [ ] A Call to Action Form Section with
  - [ ] Registration Form: New User can start the registration via a form.
  - [ ] Login Form: Existing Users can login via form.
  - [ ] Password Reset Form: Existing User can reset their password via a form.
    - [ ] Password Reset confirmation popover/confirmation. 
- [ ] An Impressa Section
  - [ ] A Contact Form: Users can contact the web service owner and developer.

***
>
***

### Components

- [ ] HTMX
- [ ] HTML Forms
- [ ] Django Forms/Formsets (Dynamic?)
- [ ] CSS Utility Framework
- [ ] Images
- [ ] JavaScript Client Framework
- [ ] Django Authentication, 
- [ ] Django CSRF
- [ ] Django Messages/Email
- [ ] Django Validators, 
- [ ] Django Sessions, 
- [ ] Django Messages (Status), 
- [ ] Django Templates
- [ ] Django URLs

***
>
***

#### **`Landing Page: Home`** for the feature: Home Page and Domain
- [ ] #81
- [ ] #82

#### **`Registration User Flow`** for the feature: Register.
- [ ] #54
   - [ ] **Option: `Embedded HTMX New Registration Form`**: in a Single Page Architectural / AJAX pattern.
       - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
       - [ ]  ⛏️ Uses: Django Form(sets), Django Authentication, Django Validators, Django CSRF, Django Messages (Email), Django Sessions, Django Messages (Status), HTMX, Django Template
- [ ] #66
   - [ ] **Option: `Separate New Registrant Confirmation Page`**: with/without page redirect to login form.
       - [ ] 👍🏽 *Benefit*: Ease implementation.
       - [ ] 👎🏽 *Trade Off*:  User has to click and navigated to login form unless an automated redirect employed.
       - [ ] 👎🏽 *Trade Off*:  A separate HTML Page for design, build, test and deploy 
       - [ ]  ⛏️ Uses: Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
   - [ ] **Option: `Embedded New Registrant Confirmation Message with redirect to Login Form`**: 
       - [ ] 👍🏽 *Benefit*: Improved User Experience, Reduces additional page need.
       - [ ] 👎🏽 *Trade Off*: Additional challenge and complexity to have in page response. 
       - [ ]  ⛏️ Uses: Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Core Login User Flow`** for the feature: Login
- [ ] #67
   - [ ] **Option: `Embedded HTMX Login Form`**: in a Single Page Architectural / AJAX pattern.
       - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
       - [ ] 👎🏽 *Trade Off*: 
       - [ ]  ⛏️ Uses: Django Form(sets), Django Authentication, Django Validators, Django CSRF, Django Messages (Email), Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
- [ ] #68
   - [ ] **Option: `Embedded Confirmation Message on Login Form`**:
       - [ ] 👍🏽 *Benefit*: Expect ease of implementation.
       - [ ] 👎🏽 *Trade Off*: 
       - [ ]  ⛏️ Uses: Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Forgot Login User Flow`** for the feature: Forgot Password.
- [ ] #69
   - [ ] **Option: `Embedded HTMX Reset Form`**: in a Single Page Architectural / AJAX pattern.
       - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
       - [ ] 👎🏽 *Trade Off*: 
       - [ ]  ⛏️ Uses: Django Form(sets), Django Authentication, Django Validators, Django CSRF, Django Messages (Email), Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
- [ ] #70
   - [ ] **Option: `Embedded Forgot Password Confirmation Message with redirect to Login Form`**:
      - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
      - [ ] 👎🏽 *Trade Off*: 
       - [ ]  ⛏️ Uses: Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#### **`Sessions User Flow`** for the feature: Remember me feature.
- [ ] #71
   - [ ] **Option: `Embedded Currently Logged In Confirmation Message Following Enabled Remember Me checkbox`**:
       - [ ] 👍🏽 *Benefit*: Improved user feedback with Confirmation in-page. 
       - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
       - [ ] 👎🏽 *Trade Off*:  
       - [ ]  ⛏️ Uses: Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
   - [ ] **Option: `Embedded Currently Logged Out Confirmation Message with redirect to Login Form/Signed Out`**:  
       - [ ] 👍🏽 *Benefit*: Improved user feedback with Confirmation in-page. 
       - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
       - [ ] 👎🏽 *Trade Off*:  
       - [ ]  ⛏️ Uses: Django Sessions, Django Messages (Status), HTMX, Django Template, Django URLs
          - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#### **`Contact Form User Flow`** for the feature: Contact Form
- [ ] #72
   - [ ] **Option: `Embedded HTMX Reset Form`**: in a Single Page Architectural / AJAX pattern.
       - [ ] 👍🏽 *Benefit*: Single page architectural pattern allows for no page refresh.
       - [ ] 👎🏽 *Trade Off*: 
       - [ ]  ⛏️ Uses: Django Form(sets), Django Authentication, Django Validators, Django CSRF, Django Messages (Email), Django URLs

***
>
***

### Acceptance 

- [ ] **`Registration User Flow`**: In the scenario of user registration of unknown or new users to the site with the intent to create a new account, then the expected outcome for a new user is to successfully register with the app/web service, and to have received a verification email to confirm the account.
    - _UA Test_: `As a user, I should be able to register a new account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Core Login User Flow`**: In the scenario of user login and authorisation of known existing users of the site, previous verified and registered, then the expected outcome for a verified known user is to successfully access with the service and to access their own user profile (i.e. the user account).
    - _UA Test_: `As a user, I should be able to login my own account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Forgot Login User Flow`**: In the scenario of forgotten user login and unable to authorisation of known existing users of the site, then the expected outcome of a forgotten password is the successful retrieval of a forgotten password link, and then the successful reset of a new password associated with the correct user and then confirmation that the user can use the new password to access their account again.
    - _UA Test_: `As a user, I should be able to reset a password to my own account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Session Management User Flow`**: In the scenario of the session and user state-based web access control and permissions, then the user should be able to stay logged in once logged in and authenticated and use the remember the user on return visits and until the cookie value is cleared or the account is timed out.
    - _UA Test_: `As a user, I should be able to leave and review the web between session, and not have re-login/re-authenticate to my account on the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- [ ] **`Contact Form User Flow`**: In the scenario of a user wanting to contact the website (owner), then the user should be able to write a message in a contact form so to send a message to the website (owner).
    - _UA Test_: `As a user, I should be able to send a message to the Dash and Do GitHub web app`.
      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

***
>
***

### Assessment Criteria
> Meets the following

- [4.03: PASS & MERIT: Access, Authentication & Authorisations](https://github.com/iPoetDev/dash-and-do-github/wiki/4.03:-PASS-&-MERIT:-Access,-Authentication-&-Authorisations-%E2%9D%93%E2%9C%94)
  - 3.1: Apply role-based login and registration functionality
  - 3.2: The current login state is reflected to the user

## Readme

-   Header:
-   Tags:
-   Notes:

## Proof

> Grammar, Spelling, Diagram,

## Editorial

-   Include
-   Edit
-   Exclude
