### ISSUE TITLE
SPRINT PLAN :: 09 [7 Days]: Release: v0.5: “Core + Accounts: Integrate, Test, Deploy”: - W/S: 23-SEP 11 | W/E: 23-SEP-16

### ISSUE THREAD

**Issue by iPoetDev** [iPoetDev/dash-and-do-github#65]
# [`SPRINT # 9?? - Release: v0.5: Core Web App & User Accounts`](https://github.com/iPoetDev/dash-and-do-github/milestone/6)

> Issue: iPoetDev/dash-and-do-github#65: SPRINT PLAN: 09 [7 Days]: Release: v0.5: “Core + Accounts: Integrate, Test, Deploy”
> https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Sprint > https://github.com/iPoetDev/dash-and-do-github/labels/Plan%20%3A%20Horizon: **5 Weeks**
> - Horizon Start: July 31
> - Horizon End: Sep 16

- Week Start: 23-Sep-11
- Week End: 23-Sep-16

## Sprint Objectives

- [ ] Integration of Front End + Backend Logic/development
- [ ] Post Implementation Testing (not TDD?)
  - Given am uncertain and learning testing, deciding to do testing after 1st concept code implementation
- [ ] Developer Decisions / ADRs;  
  - ADR000X: Unit Testing or Integration Testing or Lean TDD
  - ADD000X: Python Testing 
  - ADR000X JavaScript Testing 
- [ ] UI Testing
- [ ] User Acceptance Testing
- [ ] Documentation: Readme
- [ ] Deployment the v0.5 Live App (Heroku) 

## Spint Backlog

> Add Planned Issues Below

**VIEWS**: <small>Replace Project ID in link,</small>

-   #.
-   #.

---

## Sprint Plan | Report

-   Epic: " "
    https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Epic
-   Features:
    https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Feature
    -   :
    -   :
-   Stories:
    https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Story
    -   :
    -   :
-   Acceptance:
    https://github.com/iPoetDev/dash-and-do-github/labels/Kind%3A%20Accept
    -   :
    -   :
-   Progress:
    -   Started:
    -   Not Completed:
    -   Completed:
    -   Moved Next:

---

##### Sources

-   https://zube.io/blog/agile-project-management-workflow-for-github-issues/
